import type { Metadata } from "next";
import { Gaegu, Gamja_Flower, Quantico, Stack_Sans_Headline, Fira_Sans, Figtree } from "next/font/google";
import "./globals.css";

const gaegu = Gaegu({ 
  weight: ["300", "400", "700"], 
  subsets: ["latin"],
  variable: "--font-gaegu" 
});

const gamjaFlower = Gamja_Flower({ 
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-gamja" 
});

const quantico = Quantico({ 
  weight: ["400", "700"], 
  subsets: ["latin"],
  variable: "--font-quantico" 
});

const stack = Stack_Sans_Headline({ 
  weight: ["300", "400", "700"], 
  subsets: ["latin"],
  variable: "--font-stack" 
});

const fira = Fira_Sans({ 
  weight: ["300", "400", "700"], 
  subsets: ["latin"],
  variable: "--font-fira" 
});

const figTree = Figtree({ 
  weight: ["300", "400", "700"], 
  subsets: ["latin"],
  variable: "--font-figTree" 
});

export const metadata: Metadata = {
  title: "Chris Zhang",
  description: "Generated by Chris Zhang",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gaegu.variable} ${gamjaFlower.variable} ${figTree.variable}`}>
      <body className="font-sans bg-black min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
