import type { Metadata } from "next";
import { Gaegu, Gamja_Flower, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const gaegu = Gaegu({ 
  weight: ["300", "400", "700"], 
  subsets: ["latin"],
  variable: "--font-gaegu" 
});

const gamjaFlower = Gamja_Flower({ 
  weight: "400", 
  subsets: ["latin"],
  variable: "--font-gamja" 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gaegu.variable} ${gamjaFlower.variable}`}>
      <body className="font-sans bg-black min-h-full flex flex-col" suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
